export const data = [
  {
    id: '1',
    name: 'Compliance',
    subject: '10',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
    detail: 'Compliance',
    detailpage: [
      {
        topics: '12',
        name: 'Company ethics compliance',
      },
      {
        topics: '14',
        name: 'Company ethics compliance',
      },
      {
        topics: '13',
        name: 'Company ethics compliance',
      },
    ],
  },
  {
    id: '2',
    name: 'Health & Safety',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '3',
    name: 'Human Resources',
    subject: '12',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '4',
    name: 'Code of conduct',
    subject: '13',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '5',
    name: 'Leadership',
    subject: '10',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '6',
    name: 'Sales and Marketing',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '7',
    name: 'Talent Development',
    subject: '10',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '8',
    name: 'Compliance',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '9',
    name: 'Compliance',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '10',
    name: 'Compliance',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '11',
    name: 'Compliance',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
  {
    id: '12',
    name: 'Compliance',
    subject: '11',
    percentage: '30',
    bgColor: 'rgb(235 254 238)',
  },
];
